version: '3.8'
services:
  webdav:
    image: your-registry/webdav-demo:latest
    ports:
      - "80:8080"  # Or use port 443 for HTTPS
    volumes:
      - /path/to/production/data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 